// keygen generates the two keypairs a Hardpull CRE workflow needs and writes the secret halves
// straight into cre/.env (gitignored, 0600) without ever printing them.
//
//   - an X25519 keypair: furnishers seal position records to the public half
//     (docs/architecture.md #3.3); the enclave opens them with the private half.
//   - a secp256k1 key: signs each verdict so VerdictAttestations.sol can ecrecover it
//     (docs/architecture.md #2.1). Its ADDRESS is what you pass as CRE_SIGNER_ADDRESS when
//     deploying the contracts -- and because VerdictAttestations stores creSigner as an
//     immutable, this must be generated BEFORE `forge script Deploy`, or the contract has to
//     be redeployed.
//
// Only public values are ever written to stdout. Run from the cre/ directory:
//
//	go run ./cmd/keygen           # refuses to clobber keys that already exist
//	go run ./cmd/keygen -force    # regenerates both (invalidates every sealed record)
package main

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ethereum/go-ethereum/crypto"
	"golang.org/x/crypto/nacl/box"
)

const (
	envFile    = ".env"
	configFile = "hardpull/config.staging.json"
	// publicFile records the PUBLIC halves so scripts (and humans) can look them up later
	// without re-running keygen or parsing stdout. Nothing secret is written here.
	publicFile        = ".keys.public.json"
	x25519EnvVar      = "SECRET_WORKFLOW_X25519_PRIVATE_KEY"
	attestationEnvVar = "SECRET_ATTESTATION_SIGNER_KEY"
)

func main() {
	force := flag.Bool("force", false, "overwrite keys that already exist in .env")
	flag.Parse()

	env, err := readEnv(envFile)
	if err != nil {
		fail(err)
	}

	if !*force {
		for _, k := range []string{x25519EnvVar, attestationEnvVar} {
			if env[k] != "" {
				fail(fmt.Errorf("%s already set in %s; re-run with -force to regenerate (this invalidates every record already sealed to the current key)", k, envFile))
			}
		}
	}

	pub, priv, err := box.GenerateKey(rand.Reader)
	if err != nil {
		fail(fmt.Errorf("generating X25519 keypair: %w", err))
	}
	publicKeyHex := hex.EncodeToString(pub[:])

	signerKey, err := crypto.GenerateKey()
	if err != nil {
		fail(fmt.Errorf("generating attestation signer key: %w", err))
	}
	signerAddr := crypto.PubkeyToAddress(signerKey.PublicKey).Hex()

	env[x25519EnvVar] = hex.EncodeToString(priv[:])
	env[attestationEnvVar] = hex.EncodeToString(crypto.FromECDSA(signerKey))
	if env["CRE_TARGET"] == "" {
		env["CRE_TARGET"] = "staging-settings"
	}
	if err := writeEnv(envFile, env); err != nil {
		fail(err)
	}

	if err := setWorkflowPublicKey(configFile, publicKeyHex); err != nil {
		fail(err)
	}

	publicValues, err := json.MarshalIndent(map[string]string{
		"workflowPublicKeyHex":     publicKeyHex,
		"attestationSignerAddress": signerAddr,
	}, "", "  ")
	if err != nil {
		fail(err)
	}
	if err := os.WriteFile(publicFile, append(publicValues, '\n'), 0o644); err != nil {
		fail(fmt.Errorf("writing %s: %w", publicFile, err))
	}

	// Public values only -- the private halves live in .env and are never printed.
	fmt.Printf("Wrote secrets to %s (0600), public values to %s, and updated %s.\n\n", envFile, publicFile, configFile)
	fmt.Println("Public values -- these are safe to share, and are what the rest of the stack needs:")
	fmt.Printf("  workflow X25519 public key : %s\n", publicKeyHex)
	fmt.Printf("  attestation signer address : %s\n", signerAddr)
	fmt.Println()
	fmt.Println("Next:")
	fmt.Printf("  contracts/  deploy with CRE_SIGNER_ADDRESS=%s  (immutable once deployed)\n", signerAddr)
	fmt.Printf("  api/.env    CRE_WORKFLOW_PUBLIC_KEY_HEX=%s\n", publicKeyHex)
}

// readEnv parses a dotenv file into a map. A missing file is not an error.
func readEnv(path string) (map[string]string, error) {
	env := map[string]string{}
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return env, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		env[strings.TrimSpace(key)] = strings.TrimSpace(value)
	}
	return env, nil
}

func writeEnv(path string, env map[string]string) error {
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	// Stable order so regenerating produces a readable diff rather than a reshuffle.
	sortStrings(keys)

	var b strings.Builder
	b.WriteString("# Generated by `go run ./cmd/keygen`. Secrets -- never commit or share.\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s=%s\n", k, env[k])
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o600)
}

var publicKeyField = regexp.MustCompile(`("workflowPublicKeyHex"\s*:\s*)"[^"]*"`)

// setWorkflowPublicKey rewrites just the one field, preserving the file's comments-free JSON
// formatting rather than re-marshalling and reordering the whole config.
func setWorkflowPublicKey(path, publicKeyHex string) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("reading %s: %w", path, err)
	}
	if !publicKeyField.Match(raw) {
		return fmt.Errorf("%s has no workflowPublicKeyHex field to update", path)
	}
	updated := publicKeyField.ReplaceAll(raw, []byte(`${1}"`+publicKeyHex+`"`))

	var check map[string]any
	if err := json.Unmarshal(updated, &check); err != nil {
		return fmt.Errorf("rewriting %s produced invalid JSON: %w", path, err)
	}
	return os.WriteFile(path, updated, 0o644)
}

func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "keygen:", err)
	os.Exit(1)
}
